### ISSUE TITLE
Make sure the tests run on CI

### ISSUE THREAD

**Issue by bahmutov** [cypress-io/sinon-chai#22]
right now the circle config does not have `npm test` and it fails for latest commits but passes for commit 0a4a7a974a63cd5486aeec91c2c64e0dc7962b19

**Comment by bahmutov** [comment]
Breaking change in commit 933088c1ac4247a0142668cf813d1d3273369950 - sinon upgrade
```
Returning
       returned
         should not throw if the spy returns the correct value amongst others:
     TypeError: sinon.spy.create is not a function
      at Context.<anonymous> (test/returning.js:41:33)
```
